### ISSUE TITLE
Where is mod loaded?

### ISSUE THREAD

**Issue by kirkvogen** [phoddie/runmod#10]
I hope that you don't mind a question by way of an issue. 😀️

I'm having difficulty finding the important bit of how the module is actually loaded. Maybe I'm understanding that xsbug is actually doing the heavy lifting of that? I'm not certain.

I would like to write a "helloworld" of sorts that is a proof of concept of loading byte code dynamically. Let's say I have a simply xsa file such as your helloworld mod. I'd like to do this pseudocode:

```javascript
// I'll take the XSA file and list the bytes that make up the file. I'll just put its bytes here myself
// to keep this standalone program simple.
let xsaContent = Uint8Array.of(0x00, 0x00, ...).buffer;

// Probably other things are needed to get things ready...

// Now, load the module
let mod = loadModule(xsaContent);

// There may be other things necessary here...

// Run the module
mod.execute();

// Yay, I can see that the module ran as I see output!
```
We are excited to explore Moddable XS! We need the ability to run byte code dynamically. We've gotten dynamic execution with `eval()` working, but would prefer to execute byte code to keep memory usage smaller. I bet that my little program may need to be written in C and use the various Moddable XS functions?

**Comment by phoddie** [comment]
> I hope that you don't mind a question by way of an issue. 😀️

No problem, especially since I don't seem to have enabled Discussions on this repository.

> I'm having difficulty finding the important bit of how the module is actually loaded. Maybe I'm understanding that xsbug is actually doing the heavy lifting of that? I'm not certain.

This project uses the built-in support for mods, so the mod is loaded when the JavaScript virtual machine is initialized. [This is where](https://github.com/Moddable-OpenSource/moddable/blob/df88825e8abad3979378b7d74562c015a9d49ebb/xs/platforms/mc/xsHosts.c#L486-L488) that happens in the host.

It looks like your goal is a bit different. You want to load a mod under the control of your script at some later time. That is supported, though it is not currently in our public documentation. If that is indeed what you want to do, let me know and we'll figure something out.

In your example, you show the mod coming from an in-memory byte array. I understand that's just for simplicity. In your project, where do you expect them to reside?

> We are excited to explore Moddable XS! We need the ability to run byte code dynamically.

Cool.

> We've gotten dynamic execution with eval() working, but would prefer to execute byte code to keep memory usage smaller.

Mods will use less memory, since all the byte code and some data (strings) can remain in flash. They process of parsing the code with `eval` also uses memory which, while temporary, can be problematic with larger source code. Another benefit of mods is that they load nearly instantly, because there's no compilation step.

> I bet that my little program may need to be written in C and use the various Moddable XS functions?

Some C code may be needed. But it depends on exactly what you are trying to do, so let's break that down first. FWIW – we have some (unpublished) classes that include the C code needed in some scenarios. That allows the project to manage mod loading in script.

**Comment by kirkvogen** [comment]
Thank you for your reply! Much appreciated. I will dig in more to your comment later (I’m away from the office).

In terms of where it is coming from: it will be over HTTP. A device will access a server over HTTP to get the byte code.

**Comment by phoddie** [comment]
Thanks for the additional info.

Delivery over HTTP is possible. This example, however, assumes that the mod is installed over the xsbug communication channel which is usually serial/USB, but can also be a WebSocket (I wouldn't suggest that here, however).

It sounds like you want to deliver a mod to modify / customize the behavior of the embedded device.  The mod will remain installed until an updated mod is delivered.

If that's correct, let me know. We've done something very much like this in projects for our clients. And it can be done entirely in script. We should be able to pull together a small example for that.
